/**
 * Signs a CreatorOffer per catalog art file (generated by gen_catalog.py) with
 * DEMO_CREATOR_PRIVATE_KEY and writes catalog/catalog.json. Two offers are
 * deliberately expired / non-commercial so the demo's "rejected candidates"
 * beat is honest (our own labeled data).
 *
 * Usage: python3 scripts/gen_catalog.py && tsx scripts/seed-catalog.ts
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { sha256Hex } from "../src/server/domain/index.js";
import { loadConfig } from "../src/server/config.js";
import { PROJECT_ROOT } from "../src/server/config.js";
import { offerToTypedMessage, privateKeyToAddress, signTypedData } from "../src/server/license/eip712.js";
import { CreatorOfferSchema } from "../src/server/license/types.js";
import type { PolicyV1, UnsignedCreatorOffer } from "../src/server/license/types.js";
import { legalTextHash } from "../src/server/legal.js";

const config = loadConfig();
const creatorKey = process.env.DEMO_CREATOR_PRIVATE_KEY;
if (!creatorKey) throw new Error("DEMO_CREATOR_PRIVATE_KEY missing");
const creatorAddress = privateKeyToAddress(creatorKey);

// Pin a fixed "now" so re-running is deterministic (Date.now avoided for reproducibility).
const NOW = Number(process.env.SEED_NOW ?? 1_783_900_800); // 2026-07-12T00:00:00Z
const YEAR = 365 * 86_400;

function standardPolicy(overrides: Partial<PolicyV1> = {}): PolicyV1 {
  return {
    policyVersion: 1,
    commercialUse: true,
    channels: ["x", "linkedin", "instagram"],
    territory: "worldwide",
    maxDurationDays: 30,
    allowedTransformations: ["crop", "resize", "overlay_text"],
    modelTraining: false,
    ragIndexing: false,
    exclusive: false,
    resale: false,
    sublicensing: false,
    attributionRequired: false,
    ...overrides
  };
}



interface SeedSpec {
  slug: string;
  title: string;
  seed: number;
  tags: string[];
  policy?: Partial<PolicyV1>;
  attribution?: boolean;
  expired?: boolean;
  nonCommercial?: boolean;
}

// First-party original artworks (AI-generated by the team) — clean of any
// third-party brand, logo, or recognizable person, so they are legitimately
// licensable. Titles match the art; the flagship drives the demo narrative.
const SPECS: SeedSpec[] = [
  { slug: "cyber-dragon", title: "Ember Drake", seed: 7, tags: ["dragon", "cyberpunk", "campaign"] },
  { slug: "neon-city", title: "Neon Harbor", seed: 13, tags: ["cyberpunk", "city", "night"], attribution: true },
  { slug: "synth-portal", title: "Solar Gate", seed: 21, tags: ["synthwave", "portal", "cinematic"] },
  { slug: "aurora-koi", title: "Aurora Koi", seed: 34, tags: ["koi", "aurora", "serene"] },
  { slug: "glitch-mask", title: "Cobalt Mask", seed: 55, tags: ["mask", "cobalt", "product"] },
  // Honest demo rejects (first-party art; their reason codes are shown in the console):
  { slug: "expired-relic", title: "Bronze Relic", seed: 89, tags: ["bronze", "relic"], expired: true },
  { slug: "editorial-only", title: "Editorial Study", seed: 144, tags: ["editorial", "still-life"], nonCommercial: true }
];

const catalog: unknown[] = [];

for (const spec of SPECS) {
  const assetFile = `catalog/assets/${spec.slug}.png`;
  const previewFile = `catalog/previews/${spec.slug}.preview.png`;
  const assetPath = resolve(PROJECT_ROOT, assetFile);
  if (!existsSync(assetPath)) {
    throw new Error(`Missing art file ${assetFile} — run: python3 scripts/gen_catalog.py`);
  }
  const assetSha256 = sha256Hex(readFileSync(assetPath));

  const policy = standardPolicy({
    ...(spec.attribution ? { attributionRequired: true } : {}),
    ...(spec.nonCommercial ? { commercialUse: false } : {}),
    ...spec.policy
  });

  const unsigned: UnsignedCreatorOffer = {
    offerId: `off-${spec.slug}`,
    offerVersion: 1,
    assetId: `asset-${spec.slug}`,
    assetSha256,
    mimeType: "image/png",
    licensorWallet: creatorAddress,
    payoutWallet: creatorAddress,
    templateId: "social-commercial-v1",
    legalTextHash: legalTextHash(),
    policy,
    creatorNetPrice: "0.07",
    currency: "USDT",
    rightsAttestationHash: sha256Hex(`rights-attestation:${spec.slug}`),
    validFrom: spec.expired ? NOW - 60 * 86_400 : NOW - 30 * 86_400,
    validUntil: spec.expired ? NOW - 30 * 86_400 : NOW + YEAR,
    nonce: sha256Hex(`nonce:${spec.slug}`)
  };
  const signature = signTypedData("CreatorOffer", offerToTypedMessage(unsigned), creatorKey);
  const offer = CreatorOfferSchema.parse({ ...unsigned, signature });

  catalog.push({
    offer,
    assetFile,
    previewFile,
    title: spec.title,
    creatorDisplay: "Genesis Studio (first-party)",
    tags: spec.tags
  });
}

writeFileSync(resolve(PROJECT_ROOT, "catalog/catalog.json"), JSON.stringify(catalog, null, 2));
console.log(JSON.stringify({ creatorAddress, assets: SPECS.length, out: "catalog/catalog.json" }, null, 2));
